### PR TITLE
Create TrailerLovers

### PR DESCRIPTION
**Pull request by blooderscrew1**
A modern fullscreen theme for Playnite.

an interesting theme with a clean screen and trailer playback from the main screen

### CODE REVIEW

**Comment by blooderscrew1** [comment]
thaks for all

**Comment by JosefNemec** [comment]
Which of your two PRs is the one to verify and merge? Also they are both missing .yaml file extension.

**Comment by blooderscrew1** [comment]
> ¿Cuál de sus dos solicitudes de incorporación de cambios es la que debe verificar y fusionar? Además, a ambos les falta la extensión de archivo .yaml.

Hello,

Thanks for reviewing my pull requests. The correct PR to verify and merge is the 2°. I have added the `.yaml` extension to the file as required. Please ignore the other PR as it was a mistake on my part.

Greetings,
the link
https://github.com/blooderscrew1/TrailerLovers/blob/main/TrailerLovers.yaml

**Comment by JosefNemec** [comment]
Close bad PR then.

**Comment by blooderscrew1** [comment]
> Close bad PR then.

Is done friend thanks

**Comment by JosefNemec** [comment]
This PR is still missing .yaml file extension. Also validation via Toolbox still fails.

**Comment by JosefNemec** [comment]
Why do you have installer manifest behind some OneDrive link? Just upload it to GitHub and link to the file. See how other plugins and examples do it.

**Comment by blooderscrew1** [comment]
> Why do you have installer manifest behind some OneDrive link? Just upload it to GitHub and link to the file. See how other plugins and examples do it.

I have already made the change... I had done it because Toolox showed an error when marking a github link, but I have already changed it friend

**Comment by JosefNemec** [comment]
No you didn't change it. I can clearly see it:

image

**Comment by blooderscrew1** [comment]
> No you didn't change it. I can clearly see it:
> 
> image



forgive me, it's ready

**Comment by JosefNemec** [comment]
Still not a valid manifest file. Please, please use Toolbox to verify the manifest and also check existing manifests and examples.

**Comment by blooderscrew1** [comment]
Hello friend, I have done it... toolbox says "approved"
pass

**Comment by JosefNemec** [comment]
Screenshots will not work because they are not pointing to image files, they are pointing to a website. Please see how other plugins set this. I don't know how many times I have to say this.

**Comment by blooderscrew1** [comment]
> Screenshots will not work because they are not pointing to image files, they are pointing to a web page with an images inside of it. Please see how other plugins set this.

I want to apologize for my mistake and your time, I have already modified the screenshot links and the tollbox pass has also passed.

**Comment by JosefNemec** [comment]
First thumbnail has a typo in the url, it starts with `hhttp`

**Comment by blooderscrew1** [comment]
> La primera miniatura tiene un error tipográfico en la url, comienza con `hhttp`

oh is true, forgive me

**Pull request merged**
