### PR TITLE
Move Aniki Remix to the right folder

### PR DESCRIPTION
**Pull request by Mike-Aniki**
Sorry, my theme is all alone in a second themes_fullscreen folder, it should be moved to the real themes_fullscreen folder, I think I added an accent on the e

### CODE REVIEW

**Comment by JosefNemec** [comment]
The file is also missing .yaml extension.

**Comment by Mike-Aniki** [comment]
Sorry I'm new to this, excuse me for asking but I don't understand what you mean by extension.yaml? In my theme folder created with toolbox there is no extension.yaml , only theme.yaml

**Comment by JosefNemec** [comment]
When you upload it to GitHub you didn't set any file extension:
image

**Comment by Mike-Aniki** [comment]
I understand better, I changed it

**Pull request merged**
