### PR TITLE
Create nosyn00b_FanaticalLibrary.yaml

### PR DESCRIPTION
**Pull request by nosyn00b**
Hi,
   standard yaml file pointing to the Plugin just released.

### CODE REVIEW

**Comment by JosefNemec** [comment]
Not a valid manifest.

**Comment by JosefNemec** [comment]
Please see the specification on the main page, this is not how screenshots should be defined.

**Comment by nosyn00b** [comment]
You're obviously right Josef, I missed the field definition part, and supposed any screenshot list was ok. 
To avoid further revisions may I ask you these clarifications:
- is the missing "-" before the "image" field correct? 
- are both Image and Thumbnail fields mandatory when declaring Screenshots, and should they be in the given order?

**Comment by nosyn00b** [comment]
Hope I got it right this time: probably an example with multiple screenshots would help :).

**Pull request merged**
