### PR TITLE
Update Gerren_MindGame.yaml

### PR DESCRIPTION
**Pull request by Gerren**
updated description, better SEO

### CODE REVIEW

**Comment by Gerren** [comment]
Hi there.

I'm sorry to bother, but today I had some problems with publishing new version of the [extension](https://github.com/Gerren/Playnite-MindGame).

The [installer.yaml](https://github.com/Gerren/Playnite-MindGame/blob/master/installer.yaml) is set up (`1.04`), the Playnite recognizes it automatically and offers an update, shows `1.04`. But the built-in update, and the [install link](playnite://playnite/installaddon/gerren-mindgame) both download the old version (`1.02`).

But when I click through the [link](https://github.com/Gerren/Playnite-MindGame/releases/download/release_1_04/gerren-mindgame_1_04.pext) in the before mentioned `installer.yaml`, it downloads the `gerren-mindgame_1_04.pext` and it contains the new version (`1.04`). I installed and is really the correct version.

Or is it just buffered and I missed it...? In that case it shouldn't offer an update it cannot do (eg. buffer the `installer.yaml` as well)

Thanks a lot, I love app, and I appreciate the work you put in.

**Comment by JosefNemec** [comment]
It looks like a cache issue to me on GitHub's side:
image

**Comment by JosefNemec** [comment]
Looks a recent issue with raw links:
https://github.com/orgs/community/discussions/46773
https://github.com/orgs/community/discussions/46691
https://github.com/orgs/community/discussions/46758

**Comment by Gerren** [comment]
Ok, thanks. It's weird anyway. I can see the "raw" content updated.



2023-02-12 12_03_54-https___raw githubusercontent com_Gerren_Playnite-MindGame_master_installer yaml

**Pull request merged**
