### PR TITLE
Fix Addon ID

### PR DESCRIPTION
**Pull request by gerrykeys**
I want to fix the Addon ID of the extension

### CODE REVIEW

**Comment by JosefNemec** [comment]
As I said in the other PR. This will essentially mean that you are creating a different add-on and users that installed it using the original ID will now stop getting updates and will see this as a different extension. Are you sure you want to do this?

**Comment by gerrykeys** [comment]
Currently the updates are not detected because the addonid used to generate my extensions is different from the one specified in this manifest.
Now this is my situation:
AddonId: MAMEUtility_af854071-4cd2-47ae-a7b3-35c238f0f7c0 (from the manifest of my extension)
Id: MAMEUtility_af854071-4cd2-47ae-a7b3-35c238f0f7c0 (in the extension.yaml of my solution project)

**Comment by JosefNemec** [comment]
You could just keep using the old ID, it's not like it's breaking anything. But as you wish.

**Comment by gerrykeys** [comment]
Thanks for the support.
Now i receive correctly updates notifications.

**Pull request merged**
