### PR TITLE
Create felixkmh_AutoUpdate_Plugin.yaml

### PR DESCRIPTION
**Pull request by felixkmh**

### CODE REVIEW

**Comment by JosefNemec** [comment]
I'm not sure about this. I don't think I like an idea of supplying addon that circumvents Playnite's update system and can break down on a whim as you admit. I hope you understand.

**Comment by felixkmh** [comment]
Yeah, kind of expected that, knowing your stance on the matter. While I do admit that it could break with each Playnite update, if it does, it should simply stop doing anything, and not take down the rest of Playnite with it. I still feel that this could provide some value to some users, at their own risk of course. And while I think that each user should be able to decide whether they accept such a risk, I still understand why you wouldn't endorse that by adding it to a built-in addon browser.

**Comment by felixkmh** [comment]
And you couldn't be persuaded to add it if I added very explicit warnings to the auto-update options? These would need to be opened once anyway, because by default all options are disabled.

**Comment by JosefNemec** [comment]
Problem with these warnings is that people either don't read them or forget about them (I've seen people click through our elevation warning without reading it...). My other issue here is that it would potentially affect not just community made addons, but "built-in" ones as well.

It wouldn't be the first time some addon broke Playnite in a way it looked like it's an issue in Playnite itself, which meant I had to spend time debugging the issue. I just want to prevent that from happening. I have no issue leaving forum thread up if anybody wants to manually install this, but I don't like it being in addon db.

**Comment by felixkmh** [comment]
Good point on the built-in extensions. I will probably add an option to handle those differently. 
Understandable, spending a bunch of time on an issue that in the end turns out to be someone elses fault doesn't feel great.

**Pull request closed without merging**
