### PR TITLE
Hero

### PR DESCRIPTION
**Pull request by zeroantix**

### CODE REVIEW

**Comment by JosefNemec** [comment]
Manifest didn't pass verification:
```
IconUrl doesn't point to corret file. It needs to point to the actual file content, not its repository page.
https://github.com/zeroantix/Hero/blob/main/Media/Logo.png
SourceUrl URL is missing.
Screenshots > Thumbnail doesn't point to corret file. It needs to point to the actual file content, not its repository page.
https://github.com/zeroantix/Hero/blob/main/Media/Main.jpg
Screenshots > Image doesn't point to corret file. It needs to point to the actual file content, not its repository page.
https://github.com/zeroantix/Hero/blob/main/Media/Main.jpg
Screenshots > Thumbnail doesn't point to corret file. It needs to point to the actual file content, not its repository page.
https://github.com/zeroantix/Hero/blob/main/Media/Main%20-%20Fullscreen.jpg
Screenshots > Image doesn't point to corret file. It needs to point to the actual file content, not its repository page.
https://github.com/zeroantix/Hero/blob/main/Media/Main%20-%20Fullscreen.jpg
Screenshots > Thumbnail doesn't point to corret file. It needs to point to the actual file content, not its repository page.
https://github.com/zeroantix/Hero/blob/main/Media/Grid.jpg
Screenshots > Image doesn't point to corret file. It needs to point to the actual file content, not its repository page.
https://github.com/zeroantix/Hero/blob/main/Media/Grid.jpg
Screenshots > Thumbnail doesn't point to corret file. It needs to point to the actual file content, not its repository page.
https://github.com/zeroantix/Hero/blob/main/Media/Game%20Details.jpg
Screenshots > Image doesn't point to corret file. It needs to point to the actual file content, not its repository page.
https://github.com/zeroantix/Hero/blob/main/Media/Game%20Details.jpg
InstallerManifestUrl doesn't point to corret file. It needs to point to the actual file content, not its repository page.
```

You can use [Toolbox](https://playnite.link/docs/master/tutorials/toolbox.html) utility to verify if your manifest is valid and contains all required information.

**Comment by zeroantix** [comment]
Hey Crow. Don’t know how, but the file I added was added to the folder where it displays addon folder and readme. I must have selected  add file in the incorrect view and not realised. Can it be moved into Fullscreen folder of addons? Or do we need to delete it from where is and start again? Apologies for this :/

**Comment by JosefNemec** [comment]
I moved it

**Comment by zeroantix** [comment]
Thank you. New to this, no excuse though. Cheers :)

**Pull request merged**
