### PR TITLE
Create Aniki_ReMake.yaml

### PR DESCRIPTION
**Pull request by Mike-Aniki**

### CODE REVIEW

**Comment by Mike-Aniki** [comment]
Hi, is there a problem with my theme? I don't see it in the directory.

**Comment by JosefNemec** [comment]
Why are you opening multiple pull request for the same thing? Which one is valid?

**Comment by JosefNemec** [comment]
And the theme is visible in the db: https://playnite.link/addons.html#Aniki_Remix_df9e4536-addb-46a6-9a2c-4550c7cff461

**Comment by Mike-Aniki** [comment]
Sorry, I closed the duplicate, this is a new theme called "Aniki Remake", the one visible in the db is my other theme "Aniki Remix".

**Pull request merged**
