### PR TITLE
Create PS5ish-Slim-Remix.yaml

### PR DESCRIPTION
**Pull request by DrWolfieStein**

### CODE REVIEW

**Comment by JosefNemec** [comment]
Not a valid manifest, use Toolbox to validate and fix the manifest.

**Comment by DrWolfieStein** [comment]
Manifest updated, apologies uploaded the wrong one before. Has been verified by toolbox

**Comment by JosefNemec** [comment]
Not a valid manifest, fails via Toolbox. Also packages list should be only in installer manifest, not in this addon manifests. Please see examples in the readme here and also check existing addons.

**Comment by DrWolfieStein** [comment]
Ok, I figured out what I was doing wrong; toolbox.exe verify 'installer' will pass addon.yaml files if you include the packages; I did not realize I had been only using the 'installer' instead of 'addon'.

**Pull request merged**
