### PR TITLE
Create iSplasher_VirtualLibrary.yaml

### PR DESCRIPTION
**Pull request by iSplasher**

### CODE REVIEW

**Comment by JosefNemec** [comment]
Manifest fails validation, please use Toolbox utility to check your manifests.

https://api.playnite.link/docs/master/tutorials/toolbox.html#verify-manifests

**Comment by iSplasher** [comment]
It keeps failing, and I'm not sure why? The purported URL is reachable.
billede

**Comment by JosefNemec** [comment]
Check if AV or FW is not blocking Toolbox from network access.

**Comment by iSplasher** [comment]
Everything passes now.

**Pull request merged**
