### PR TITLE
Change Add-on ID to Resolve Conflict with Existing Add-ons

### PR DESCRIPTION
**Pull request by yuuta0331**
The Add-on ID has been updated to resolve conflicts with existing add-ons.

### CODE REVIEW

**Comment by JosefNemec** [comment]
There is no conflict with the other addon as it has different ID and changing yours now would break updates for people that have your already installed. So unless you have some other good reason for this change, I'm closing this.

**Comment by yuuta0331** [comment]
Thank you for your response. I understand that changing the ID now would disrupt updates for current users. However, my concern stems from the fact that the extension.yaml ID was previously set to "FanzaMetadata," which led to Playnite prompting updates for erri120's FanzaMetadata plugin instead of mine.

To avoid such issues and ensure proper separation between the two plugins, I updated the ID to a unique value. If this concern has already been resolved, or if the current setup guarantees no conflicts, I am happy to proceed without further changes.

**Comment by yuuta0331** [comment]
I have confirmed that changing only the Id in `extension.yaml` prevents updates for erri120's FanzaMetadata plugin from being prompted. Therefore, if it is not required for the `extension.yaml` Id to match, there is no issue.

**Comment by yuuta0331** [comment]
I will resolve the issue by changing only the Id in `extension.yaml`.  
Closing this pull request.

**Comment by JosefNemec** [comment]
> if it is not required for the extension.yaml Id to match, there is no issue

It totally is required for IDs to match, otherwise Playnite will think that your plugin is different plugin.

**Comment by JosefNemec** [comment]
You simply must have `FanzaMetadata_db03c8d9-645a-4359-aafb-01cda945f301` in all manifests. If you are going mix and match these IDs, then there will be issues.

**Pull request closed without merging**
