### PR TITLE
Create Twiggy547_Magpie9.yaml

### PR DESCRIPTION
**Pull request by Twiggy547**

### CODE REVIEW

**Comment by JosefNemec** [comment]
All links in the manifest ware wrong, they point to GitHub page for that file, not to the actual (raw) file content.

**Comment by Twiggy547** [comment]
Oops thank you for pointing that out. ill fix it but may put this on wait since the original author just put out his own update to his theme.

**Comment by JosefNemec** [comment]
Screenshots section is wrong, missing thumbnails.

**Comment by Twiggy547** [comment]
thank you!

**Pull request merged**
