### PR TITLE
Create Archemedian_ES-DE-PN-FE.yaml

### PR DESCRIPTION
**Pull request by ArchemedIan**

### CODE REVIEW

**Comment by JosefNemec** [comment]
Can you please add some description that tells users what this actually does? Thank you

Also it's Playnite, not PlayNite ;)

**Comment by ArchemedIan** [comment]
> Can you please add some description that tells users what this actually does? Thank you

done.

> Also it's Playnite, not PlayNite ;)

yes that was to show why the extension is named the way it is; its also why i put `EmulationStation` and `FrontEnd` instead of `Emulationstation` and `Frontend.`

 I can change it if spelling it correctly in the full description will not suffice

**Comment by JosefNemec** [comment]
I don't want to sound pedantic, but it says "for PlayNite" an Playnite is spelled Play**n**ite. Please fix it.

**Comment by ArchemedIan** [comment]
> I don't want to sound pedantic, but it says "for PlayNite" and Playnite is spelled Play**n**ite. Please fix it.

it isn't pedantic, because you're not correcting an error (nor are you doing it annoyingly.) this was intentional. all due respect, the plugin is called "EmulationStation Desktop Edition FrontEnd for PlayNite" or ES-DE-FE-PN for short. the `n` is capitalized because it is part of the plugin name, not because it is the correct spelling of the program Playnite. the plugin is not called "ES-DE-FE (for Playnite)" that would imply the plugin IS the frontend, and that its a plugin available for more than Playnite. 

to put it as simply as you put it. the plugin is spelled `ES-DE-FE-PN` not `ES-DE-FE-Pn` 

I will change it if absolutely necessary, but I implore you to reconsider.

**Pull request merged**
