### PR TITLE
Add Steam Chat Plugin

### PR DESCRIPTION
**Pull request by uwx**

### CODE REVIEW

**Comment by uwx** [comment]
I had some issue with the WebView when I developed this plugin, but I don't remember why. I will look into it and get back to you.

**Comment by uwx** [comment]
Okay, I remember the issue: I think in the SDK so far there is no WebView that exposes a `CefSharp.Wpf.ChromiumWebBrowser` (which extends `Control`, and so can be embedded in the sidebar item). 
As such I think it's presently not possible to embed the Steam chat in the sidebar other than having it be a popup window.

My workaround here was to reference CefSharp directly, which yes it is a bad practice, however at least in theory I think if Playnite updates to a newer version of CefSharp, as long as the API is compatible, it should still satisfy the assembly reference in the plugin. Either way if the CefSharp API changes between versions that would in fact break the plugin.

I think my options here are to either embed a separate version of CefSharp (I used to do this previously, both versions would work concurrently and shouldn't interact with each other), use another library like WebView2, or wait for the SDK to support exposing a WPF browser control. I may be able to PR that as a feature if you'd accept that.

Let me know how you'd like me to proceed.

**Comment by JosefNemec** [comment]
> wait for the SDK to support exposing a WPF browser control

This should be preferred solution. I'll add it in P10, I'm already working on some other web view related changes so I'll include it.

> embed a separate version of CefSharp

You can't do that. .NET Framework doesn't allow you to load multiple versions of the same assembly into the same process (app domain).

> use another library like WebView2

Probably your only option right now if you don't want to wait for P10.

**Comment by uwx** [comment]
I've adapted the plugin to use WebView2 now.

**Pull request merged**
